### ISSUE TITLE
Hair style export tool

### ISSUE THREAD

**Issue by econundrum** [Upliner/CharMorph-db#1]
Did you create a tool for exporting the particle hair styles to the .npz files.

Could you integrate the ability to export hair styles that users create for use on future characters?

**Comment by Upliner** [comment]
Of course I have such tool. It's right here in CharMorph.
![export_hair](https://user-images.githubusercontent.com/180094/109402938-a19b5680-7962-11eb-8dc0-cc69e0ee7c7b.png)
But you should know that currently CharMorph requires both .blend and .npz files to import hair. But maybe in future .npz won't be required. Currenly I have an experimental branch that doesn't require .npz files for hair but it isn't merged to master yet.
If you have more question about CharMorph character creation you can contact me at MB-Lab Discord server. It will be much quicker :)

https://discord.gg/FuJGcVN

But if you prefer to talk on GitHub it's better to post issues to main CharMorph repository because I check it much more frequently than this one.
